name: Build

on:
  push:
    branches: [ master, framework ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
  
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore Dotuna.csproj

    - name: Build project
      run: msbuild Dotuna.csproj /p:Configuration=Release

    - uses: actions/upload-artifact@v4
      with:
        name: Dotuna
        path: ./bin/Release/Dotuna.exe
