name: Build

on:
  push:
    branches: [ master, framework ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: microsoft/setup-msbuild@v1.3
    - run: msbuild Dotuna.csproj /p:Configuration=Release
    - run: ls ./bin/Release
    - uses: actions/upload-artifact@v4
      with:
        name: WinFormsApp
        path: ./bin/Release/Dotuna.exe
